const $ = (s) => document.querySelector(s);
const stageNames = ['Planner', 'Coverage critic', 'Generator', 'Executor', 'Healer'];
let events = 0;
$('#demoMode').addEventListener('change', (e) => $('#modeHint').textContent = e.target.checked ? 'Showcase mode uses a deterministic checkout scenario so your demo remains reliable. Turn it off to inspect a live target with Playwright installed.' : 'Live mode will explore the supplied URL. Configure a browser engine and target credentials before presenting live results.');
$('#runForm').addEventListener('submit', async (event) => {
  event.preventDefault(); events = 0; $('#eventCount').textContent = '0 events'; $('#emptyState').hidden = true; $('#mission').hidden = false; $('#runButton').disabled = true; $('#runButton').textContent = 'Orchestrating…'; $('#runStatus').textContent = 'Running';
  $('#feed').innerHTML=''; $('#plan').innerHTML=''; $('#tests').innerHTML=''; $('#healing').innerHTML=''; $('#report').innerHTML='<span class="muted">Synthesising evidence…</span>'; renderStages();
  const body = { url: $('#url').value, intent: $('#intent').value, prd: $('#prd').value, demoMode: $('#demoMode').checked };
  try { const response = await fetch('/api/runs', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(body) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); stream(payload.id); } catch(error) { finish(`Could not start: ${error.message}`); }
});
function stream(id) { const stream = new EventSource(`/api/runs/${id}/events`); stream.onmessage = (e) => { const event=JSON.parse(e.data); handle(event); if(event.type==='run.complete'||event.type==='run.failed'){stream.close(); finish(event.type==='run.failed'?event.payload.message:'Mission complete');} }; stream.onerror=()=>{stream.close();finish('Connection interrupted');}; }
function handle(event){events++;$('#eventCount').textContent=`${events} events`;if(event.type==='stage.started'){setStage(event.payload.name,'active');feed(event.payload.name,'Agent has started evaluating this stage.',event.at)}if(event.type==='stage.completed'){setStage(event.payload.name,'complete')}if(event.type==='planner.plan-ready')renderPlan(event.payload.plan);if(event.type==='critic.coverage-reviewed')feed('Coverage critic',`${event.payload.score}% coverage confidence. ${event.payload.gaps.length} explicit risk(s) retained.`,event.at);if(event.type==='generator.tests-ready')renderTests(event.payload.tests);if(event.type==='executor.results-ready')renderTests(event.payload.outcomes);if(event.type==='healer.interventions-ready')renderHealing(event.payload.interventions);if(event.type==='report.ready')renderReport(event.payload);if(!['stage.started','stage.completed','planner.plan-ready','critic.coverage-reviewed','generator.tests-ready','executor.results-ready','healer.interventions-ready','report.ready'].includes(event.type))feed(event.type,brief(event.payload),event.at)}
function renderStages(){ $('#stages').innerHTML=stageNames.map((n,i)=>`<div class="stage" data-stage="${n}"><span class="stage-num">0${i+1}</span><div class="stage-name">${n}</div></div>`).join('');}
function setStage(name,state){const needle=stageNames.find(n=>name.startsWith(n));const el=[...document.querySelectorAll('.stage')].find(x=>x.dataset.stage===needle);if(el){if(state==='active')[...document.querySelectorAll('.stage')].forEach(x=>{if(x!==el&&x.classList.contains('active'))x.classList.replace('active','complete')});el.classList.remove('active','complete');el.classList.add(state)}}
function feed(title,text,at){const time=at?new Date(at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'}):'now';$('#feed').insertAdjacentHTML('afterbegin',`<div class="event"><time>${time}</time><strong>${escape(title)}</strong><p>${escape(text)}</p></div>`)}
function renderPlan(plan){$('#plan').innerHTML=plan.scenarios.map(s=>`<div class="card"><span class="badge">${s.risk} · ${s.type}</span><strong>${escape(s.id)} · ${escape(s.title)}</strong><p>${escape(s.expected)}</p></div>`).join('')}
function renderTests(tests){$('#tests').innerHTML=tests.map(t=>`<div class="card ${t.status==='failed'?'fail':''}"><span class="badge">${escape(t.status||t.selectorStatus)}</span><strong>${escape(t.id)} · ${escape(t.title)}</strong><p>${escape(t.evidence||`Selector ${t.selectorStatus}.`)}</p></div>`).join('')}
function renderHealing(items){$('#healing').innerHTML=items.length?items.map(h=>`<div class="card"><span class="badge heal">${escape(h.result)}</span><strong>${escape(h.testId)} · ${escape(h.classification)}</strong><p>${escape(h.action)}<br/>Confidence: ${Math.round(h.confidence*100)}%</p></div>`).join(''):'<p class="muted">No failed generated test required healing.</p>'}
function renderReport(r){$('#report').innerHTML=`<div class="score">${r.coverageScore}%</div><h4>${escape(r.verdict)}</h4><p>${escape(r.summary)}</p><div class="report-grid"><div class="metric"><b>${r.scenariosCovered}</b>scenarios</div><div class="metric"><b>${r.passed}</b>passing</div><div class="metric"><b>${r.healed}</b>healed</div><div class="metric"><b>${r.remainingRisk.length}</b>risks left</div></div><p class="muted">Remaining: ${escape(r.remainingRisk.map(x=>x.area).join(', ')||'No material gaps identified')}</p>`}
function brief(v){return typeof v==='object'?Object.keys(v).join(', '):String(v)}function escape(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function finish(message){$('#runStatus').textContent=message;$('#runButton').disabled=false;$('#runButton').innerHTML='Launch test mission <span>→</span>';}
